# This is a basic workflow
# @nirgeier

# Display name of workflow
name: 01 - Basic Shell workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  # List of events which will trigger the workflow
  push:
    branches: ["main"]

# Optional: Environment variables
env:
  author: CodeWizard

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on, in this case a Linus hosted runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Send greeting
        run: |
          echo "Hello ${{ env.author }}"
