# Display name of workflow
name: Chaining Jobs

# Display name under teh actions tab
run-name: "Workflow triggered by user: by @${{ github.actor }}"

on:
  # Allow manually triggered using the UI or API.
  workflow_dispatch:
    # Inputs for the workflow.
    inputs:
      # We will use this to demonstrate how to use input variables
      # Usage: ${{ github.event.inputs.job3-inputs }}
      job3-inputs:
        # Human description
        description: "Run job 3"
        # Is this value required?
        required: true
        # The input type, in this case boolean
        type: boolean

jobs:

  job-01:
    name: Job 01
    runs-on: ubuntu-latest
    steps:
    - name: Output for Job 1
      run: echo "Job 01 Run Job 3 equals ${{ github.event.inputs.job3-inputs }}" 

  job-2:
    name: Job 2
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
    - name: Output for Job 2
      run: echo "Hello from Job 2"

  job-3:
    name: Job 3
    if: github.event.inputs.job3-inputs == 'true'
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
    - name: Output for Job 3
      run: echo "Hello from Job 3"

  job-4:
    name: Job 4
    runs-on: ubuntu-latest
    # if: always()
    needs:
      - job-2
      - job-3
    steps:
    - name: Output for Job 4
      run: echo "Hello from Job 4"
        